// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.catalog;

import com.raze.coleadmin.catalog.EstatusInscripcion;
import com.raze.coleadmin.catalog.EstatusInscripcionDataOnDemand;
import com.raze.coleadmin.domain.Usuario;
import com.raze.coleadmin.repository.EstatusInscripcionRepository;
import com.raze.coleadmin.service.EstatusInscripcionService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EstatusInscripcionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EstatusInscripcionDataOnDemand: @Component;
    
    private Random EstatusInscripcionDataOnDemand.rnd = new SecureRandom();
    
    private List<EstatusInscripcion> EstatusInscripcionDataOnDemand.data;
    
    @Autowired
    EstatusInscripcionService EstatusInscripcionDataOnDemand.estatusInscripcionService;
    
    @Autowired
    EstatusInscripcionRepository EstatusInscripcionDataOnDemand.estatusInscripcionRepository;
    
    public EstatusInscripcion EstatusInscripcionDataOnDemand.getNewTransientEstatusInscripcion(int index) {
        EstatusInscripcion obj = new EstatusInscripcion();
        setActivo(obj, index);
        setDescripcion(obj, index);
        setFechaCreacion(obj, index);
        setFechaModificacion(obj, index);
        setNombreEstatusInscripcion(obj, index);
        setUsuarioCrea(obj, index);
        setUsuarioModifica(obj, index);
        return obj;
    }
    
    public void EstatusInscripcionDataOnDemand.setActivo(EstatusInscripcion obj, int index) {
        Boolean activo = Boolean.TRUE;
        obj.setActivo(activo);
    }
    
    public void EstatusInscripcionDataOnDemand.setDescripcion(EstatusInscripcion obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void EstatusInscripcionDataOnDemand.setFechaCreacion(EstatusInscripcion obj, int index) {
        Date fechaCreacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaCreacion(fechaCreacion);
    }
    
    public void EstatusInscripcionDataOnDemand.setFechaModificacion(EstatusInscripcion obj, int index) {
        Date fechaModificacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaModificacion(fechaModificacion);
    }
    
    public void EstatusInscripcionDataOnDemand.setNombreEstatusInscripcion(EstatusInscripcion obj, int index) {
        String nombreEstatusInscripcion = "nombreEstatusInscripcion_" + index;
        obj.setNombreEstatusInscripcion(nombreEstatusInscripcion);
    }
    
    public void EstatusInscripcionDataOnDemand.setUsuarioCrea(EstatusInscripcion obj, int index) {
        Usuario usuarioCrea = null;
        obj.setUsuarioCrea(usuarioCrea);
    }
    
    public void EstatusInscripcionDataOnDemand.setUsuarioModifica(EstatusInscripcion obj, int index) {
        Usuario usuarioModifica = null;
        obj.setUsuarioModifica(usuarioModifica);
    }
    
    public EstatusInscripcion EstatusInscripcionDataOnDemand.getSpecificEstatusInscripcion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EstatusInscripcion obj = data.get(index);
        Long id = obj.getId();
        return estatusInscripcionService.findEstatusInscripcion(id);
    }
    
    public EstatusInscripcion EstatusInscripcionDataOnDemand.getRandomEstatusInscripcion() {
        init();
        EstatusInscripcion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return estatusInscripcionService.findEstatusInscripcion(id);
    }
    
    public boolean EstatusInscripcionDataOnDemand.modifyEstatusInscripcion(EstatusInscripcion obj) {
        return false;
    }
    
    public void EstatusInscripcionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = estatusInscripcionService.findEstatusInscripcionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EstatusInscripcion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EstatusInscripcion>();
        for (int i = 0; i < 10; i++) {
            EstatusInscripcion obj = getNewTransientEstatusInscripcion(i);
            try {
                estatusInscripcionService.saveEstatusInscripcion(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            estatusInscripcionRepository.flush();
            data.add(obj);
        }
    }
    
}
