// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.catalog;

import com.raze.coleadmin.catalog.EstatusCargo;
import com.raze.coleadmin.catalog.EstatusCargoDataOnDemand;
import com.raze.coleadmin.domain.Usuario;
import com.raze.coleadmin.repository.EstatusCargoRepository;
import com.raze.coleadmin.service.EstatusCargoService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EstatusCargoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EstatusCargoDataOnDemand: @Component;
    
    private Random EstatusCargoDataOnDemand.rnd = new SecureRandom();
    
    private List<EstatusCargo> EstatusCargoDataOnDemand.data;
    
    @Autowired
    EstatusCargoService EstatusCargoDataOnDemand.estatusCargoService;
    
    @Autowired
    EstatusCargoRepository EstatusCargoDataOnDemand.estatusCargoRepository;
    
    public EstatusCargo EstatusCargoDataOnDemand.getNewTransientEstatusCargo(int index) {
        EstatusCargo obj = new EstatusCargo();
        setActivo(obj, index);
        setDescripcion(obj, index);
        setFechaCreacion(obj, index);
        setFechaModificacion(obj, index);
        setNombreEstatusCargo(obj, index);
        setUsuarioCrea(obj, index);
        setUsuarioModifica(obj, index);
        return obj;
    }
    
    public void EstatusCargoDataOnDemand.setActivo(EstatusCargo obj, int index) {
        Boolean activo = Boolean.TRUE;
        obj.setActivo(activo);
    }
    
    public void EstatusCargoDataOnDemand.setDescripcion(EstatusCargo obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void EstatusCargoDataOnDemand.setFechaCreacion(EstatusCargo obj, int index) {
        Date fechaCreacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaCreacion(fechaCreacion);
    }
    
    public void EstatusCargoDataOnDemand.setFechaModificacion(EstatusCargo obj, int index) {
        Date fechaModificacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaModificacion(fechaModificacion);
    }
    
    public void EstatusCargoDataOnDemand.setNombreEstatusCargo(EstatusCargo obj, int index) {
        String nombreEstatusCargo = "nombreEstatusCargo_" + index;
        obj.setNombreEstatusCargo(nombreEstatusCargo);
    }
    
    public void EstatusCargoDataOnDemand.setUsuarioCrea(EstatusCargo obj, int index) {
        Usuario usuarioCrea = null;
        obj.setUsuarioCrea(usuarioCrea);
    }
    
    public void EstatusCargoDataOnDemand.setUsuarioModifica(EstatusCargo obj, int index) {
        Usuario usuarioModifica = null;
        obj.setUsuarioModifica(usuarioModifica);
    }
    
    public EstatusCargo EstatusCargoDataOnDemand.getSpecificEstatusCargo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EstatusCargo obj = data.get(index);
        Long id = obj.getId();
        return estatusCargoService.findEstatusCargo(id);
    }
    
    public EstatusCargo EstatusCargoDataOnDemand.getRandomEstatusCargo() {
        init();
        EstatusCargo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return estatusCargoService.findEstatusCargo(id);
    }
    
    public boolean EstatusCargoDataOnDemand.modifyEstatusCargo(EstatusCargo obj) {
        return false;
    }
    
    public void EstatusCargoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = estatusCargoService.findEstatusCargoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EstatusCargo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EstatusCargo>();
        for (int i = 0; i < 10; i++) {
            EstatusCargo obj = getNewTransientEstatusCargo(i);
            try {
                estatusCargoService.saveEstatusCargo(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            estatusCargoRepository.flush();
            data.add(obj);
        }
    }
    
}
