// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.catalog;

import com.raze.coleadmin.catalog.MetodoPago;
import com.raze.coleadmin.catalog.MetodoPagoDataOnDemand;
import com.raze.coleadmin.domain.Usuario;
import com.raze.coleadmin.repository.MetodoPagoRepository;
import com.raze.coleadmin.service.MetodoPagoService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MetodoPagoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MetodoPagoDataOnDemand: @Component;
    
    private Random MetodoPagoDataOnDemand.rnd = new SecureRandom();
    
    private List<MetodoPago> MetodoPagoDataOnDemand.data;
    
    @Autowired
    MetodoPagoService MetodoPagoDataOnDemand.metodoPagoService;
    
    @Autowired
    MetodoPagoRepository MetodoPagoDataOnDemand.metodoPagoRepository;
    
    public MetodoPago MetodoPagoDataOnDemand.getNewTransientMetodoPago(int index) {
        MetodoPago obj = new MetodoPago();
        setActivo(obj, index);
        setDescripcion(obj, index);
        setFechaCreacion(obj, index);
        setFechaModificacion(obj, index);
        setNombreMetodoPago(obj, index);
        setUsuarioCrea(obj, index);
        setUsuarioModifica(obj, index);
        return obj;
    }
    
    public void MetodoPagoDataOnDemand.setActivo(MetodoPago obj, int index) {
        Boolean activo = Boolean.TRUE;
        obj.setActivo(activo);
    }
    
    public void MetodoPagoDataOnDemand.setDescripcion(MetodoPago obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void MetodoPagoDataOnDemand.setFechaCreacion(MetodoPago obj, int index) {
        Date fechaCreacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaCreacion(fechaCreacion);
    }
    
    public void MetodoPagoDataOnDemand.setFechaModificacion(MetodoPago obj, int index) {
        Date fechaModificacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaModificacion(fechaModificacion);
    }
    
    public void MetodoPagoDataOnDemand.setNombreMetodoPago(MetodoPago obj, int index) {
        String nombreMetodoPago = "nombreMetodoPago_" + index;
        obj.setNombreMetodoPago(nombreMetodoPago);
    }
    
    public void MetodoPagoDataOnDemand.setUsuarioCrea(MetodoPago obj, int index) {
        Usuario usuarioCrea = null;
        obj.setUsuarioCrea(usuarioCrea);
    }
    
    public void MetodoPagoDataOnDemand.setUsuarioModifica(MetodoPago obj, int index) {
        Usuario usuarioModifica = null;
        obj.setUsuarioModifica(usuarioModifica);
    }
    
    public MetodoPago MetodoPagoDataOnDemand.getSpecificMetodoPago(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MetodoPago obj = data.get(index);
        Long id = obj.getId();
        return metodoPagoService.findMetodoPago(id);
    }
    
    public MetodoPago MetodoPagoDataOnDemand.getRandomMetodoPago() {
        init();
        MetodoPago obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return metodoPagoService.findMetodoPago(id);
    }
    
    public boolean MetodoPagoDataOnDemand.modifyMetodoPago(MetodoPago obj) {
        return false;
    }
    
    public void MetodoPagoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = metodoPagoService.findMetodoPagoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MetodoPago' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MetodoPago>();
        for (int i = 0; i < 10; i++) {
            MetodoPago obj = getNewTransientMetodoPago(i);
            try {
                metodoPagoService.saveMetodoPago(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            metodoPagoRepository.flush();
            data.add(obj);
        }
    }
    
}
