// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.catalog;

import com.raze.coleadmin.catalog.NivelEducativoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NivelEducativoIntegrationTest_Roo_Configurable {
    
    declare @type: NivelEducativoIntegrationTest: @Configurable;
    
}
