// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.catalog;

import com.raze.coleadmin.catalog.TipoAsistenciaIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoAsistenciaIntegrationTest_Roo_Configurable {
    
    declare @type: TipoAsistenciaIntegrationTest: @Configurable;
    
}
