// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.domain;

import com.raze.coleadmin.domain.AlumnoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AlumnoIntegrationTest_Roo_Configurable {
    
    declare @type: AlumnoIntegrationTest: @Configurable;
    
}
