// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.domain;

import com.raze.coleadmin.domain.CargoDataOnDemand;
import com.raze.coleadmin.domain.CargoIntegrationTest;
import com.raze.coleadmin.repository.CargoRepository;
import com.raze.coleadmin.service.CargoService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CargoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CargoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CargoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CargoIntegrationTest: @Transactional;
    
    @Autowired
    CargoDataOnDemand CargoIntegrationTest.dod;
    
    @Autowired
    CargoService CargoIntegrationTest.cargoService;
    
    @Autowired
    CargoRepository CargoIntegrationTest.cargoRepository;
    
    @Test
    public void CargoIntegrationTest.testCountAllCargoes() {
        Assert.assertNotNull("Data on demand for 'Cargo' failed to initialize correctly", dod.getRandomCargo());
        long count = cargoService.countAllCargoes();
        Assert.assertTrue("Counter for 'Cargo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CargoIntegrationTest.testFindCargo() {
        Cargo obj = dod.getRandomCargo();
        Assert.assertNotNull("Data on demand for 'Cargo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cargo' failed to provide an identifier", id);
        obj = cargoService.findCargo(id);
        Assert.assertNotNull("Find method for 'Cargo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Cargo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CargoIntegrationTest.testFindAllCargoes() {
        Assert.assertNotNull("Data on demand for 'Cargo' failed to initialize correctly", dod.getRandomCargo());
        long count = cargoService.countAllCargoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Cargo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Cargo> result = cargoService.findAllCargoes();
        Assert.assertNotNull("Find all method for 'Cargo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Cargo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CargoIntegrationTest.testFindCargoEntries() {
        Assert.assertNotNull("Data on demand for 'Cargo' failed to initialize correctly", dod.getRandomCargo());
        long count = cargoService.countAllCargoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Cargo> result = cargoService.findCargoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Cargo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Cargo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CargoIntegrationTest.testSaveCargo() {
        Assert.assertNotNull("Data on demand for 'Cargo' failed to initialize correctly", dod.getRandomCargo());
        Cargo obj = dod.getNewTransientCargo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Cargo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Cargo' identifier to be null", obj.getId());
        try {
            cargoService.saveCargo(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        cargoRepository.flush();
        Assert.assertNotNull("Expected 'Cargo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CargoIntegrationTest.testDeleteCargo() {
        Cargo obj = dod.getRandomCargo();
        Assert.assertNotNull("Data on demand for 'Cargo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cargo' failed to provide an identifier", id);
        obj = cargoService.findCargo(id);
        cargoService.deleteCargo(obj);
        cargoRepository.flush();
        Assert.assertNull("Failed to remove 'Cargo' with identifier '" + id + "'", cargoService.findCargo(id));
    }
    
}
