// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.domain;

import com.raze.coleadmin.domain.PersonalDataOnDemand;
import com.raze.coleadmin.domain.PersonalIntegrationTest;
import com.raze.coleadmin.repository.PersonalRepository;
import com.raze.coleadmin.service.PersonalService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersonalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PersonalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PersonalIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PersonalIntegrationTest: @Transactional;
    
    @Autowired
    PersonalDataOnDemand PersonalIntegrationTest.dod;
    
    @Autowired
    PersonalService PersonalIntegrationTest.personalService;
    
    @Autowired
    PersonalRepository PersonalIntegrationTest.personalRepository;
    
    @Test
    public void PersonalIntegrationTest.testCountAllPersonals() {
        Assert.assertNotNull("Data on demand for 'Personal' failed to initialize correctly", dod.getRandomPersonal());
        long count = personalService.countAllPersonals();
        Assert.assertTrue("Counter for 'Personal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PersonalIntegrationTest.testFindPersonal() {
        Personal obj = dod.getRandomPersonal();
        Assert.assertNotNull("Data on demand for 'Personal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Personal' failed to provide an identifier", id);
        obj = personalService.findPersonal(id);
        Assert.assertNotNull("Find method for 'Personal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Personal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PersonalIntegrationTest.testFindAllPersonals() {
        Assert.assertNotNull("Data on demand for 'Personal' failed to initialize correctly", dod.getRandomPersonal());
        long count = personalService.countAllPersonals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Personal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Personal> result = personalService.findAllPersonals();
        Assert.assertNotNull("Find all method for 'Personal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Personal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PersonalIntegrationTest.testFindPersonalEntries() {
        Assert.assertNotNull("Data on demand for 'Personal' failed to initialize correctly", dod.getRandomPersonal());
        long count = personalService.countAllPersonals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Personal> result = personalService.findPersonalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Personal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Personal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PersonalIntegrationTest.testSavePersonal() {
        Assert.assertNotNull("Data on demand for 'Personal' failed to initialize correctly", dod.getRandomPersonal());
        Personal obj = dod.getNewTransientPersonal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Personal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Personal' identifier to be null", obj.getId());
        try {
            personalService.savePersonal(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        personalRepository.flush();
        Assert.assertNotNull("Expected 'Personal' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PersonalIntegrationTest.testDeletePersonal() {
        Personal obj = dod.getRandomPersonal();
        Assert.assertNotNull("Data on demand for 'Personal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Personal' failed to provide an identifier", id);
        obj = personalService.findPersonal(id);
        personalService.deletePersonal(obj);
        personalRepository.flush();
        Assert.assertNull("Failed to remove 'Personal' with identifier '" + id + "'", personalService.findPersonal(id));
    }
    
}
