// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.domain;

import com.raze.coleadmin.domain.Escuela;
import com.raze.coleadmin.domain.EscuelaDataOnDemand;
import com.raze.coleadmin.domain.Salon;
import com.raze.coleadmin.domain.SalonDataOnDemand;
import com.raze.coleadmin.domain.Usuario;
import com.raze.coleadmin.repository.SalonRepository;
import com.raze.coleadmin.service.SalonService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SalonDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SalonDataOnDemand: @Component;
    
    private Random SalonDataOnDemand.rnd = new SecureRandom();
    
    private List<Salon> SalonDataOnDemand.data;
    
    @Autowired
    EscuelaDataOnDemand SalonDataOnDemand.escuelaDataOnDemand;
    
    @Autowired
    SalonService SalonDataOnDemand.salonService;
    
    @Autowired
    SalonRepository SalonDataOnDemand.salonRepository;
    
    public Salon SalonDataOnDemand.getNewTransientSalon(int index) {
        Salon obj = new Salon();
        setActivo(obj, index);
        setDescripcion(obj, index);
        setEscuela(obj, index);
        setFechaCreacion(obj, index);
        setFechaModificacion(obj, index);
        setNombreSalon(obj, index);
        setUsuarioCrea(obj, index);
        setUsuarioModifica(obj, index);
        return obj;
    }
    
    public void SalonDataOnDemand.setActivo(Salon obj, int index) {
        Boolean activo = Boolean.TRUE;
        obj.setActivo(activo);
    }
    
    public void SalonDataOnDemand.setDescripcion(Salon obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void SalonDataOnDemand.setEscuela(Salon obj, int index) {
        Escuela escuela = escuelaDataOnDemand.getRandomEscuela();
        obj.setEscuela(escuela);
    }
    
    public void SalonDataOnDemand.setFechaCreacion(Salon obj, int index) {
        Date fechaCreacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaCreacion(fechaCreacion);
    }
    
    public void SalonDataOnDemand.setFechaModificacion(Salon obj, int index) {
        Date fechaModificacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaModificacion(fechaModificacion);
    }
    
    public void SalonDataOnDemand.setNombreSalon(Salon obj, int index) {
        String nombreSalon = "nombreSalon_" + index;
        obj.setNombreSalon(nombreSalon);
    }
    
    public void SalonDataOnDemand.setUsuarioCrea(Salon obj, int index) {
        Usuario usuarioCrea = null;
        obj.setUsuarioCrea(usuarioCrea);
    }
    
    public void SalonDataOnDemand.setUsuarioModifica(Salon obj, int index) {
        Usuario usuarioModifica = null;
        obj.setUsuarioModifica(usuarioModifica);
    }
    
    public Salon SalonDataOnDemand.getSpecificSalon(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Salon obj = data.get(index);
        Long id = obj.getId();
        return salonService.findSalon(id);
    }
    
    public Salon SalonDataOnDemand.getRandomSalon() {
        init();
        Salon obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return salonService.findSalon(id);
    }
    
    public boolean SalonDataOnDemand.modifySalon(Salon obj) {
        return false;
    }
    
    public void SalonDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = salonService.findSalonEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Salon' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Salon>();
        for (int i = 0; i < 10; i++) {
            Salon obj = getNewTransientSalon(i);
            try {
                salonService.saveSalon(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            salonRepository.flush();
            data.add(obj);
        }
    }
    
}
