// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.service;

import com.raze.coleadmin.domain.ConceptoInscripcionCurso;
import com.raze.coleadmin.repository.ConceptoInscripcionCursoRepository;
import com.raze.coleadmin.service.ConceptoInscripcionCursoServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConceptoInscripcionCursoServiceImpl_Roo_Service {
    
    declare @type: ConceptoInscripcionCursoServiceImpl: @Service;
    
    declare @type: ConceptoInscripcionCursoServiceImpl: @Transactional;
    
    @Autowired
    ConceptoInscripcionCursoRepository ConceptoInscripcionCursoServiceImpl.conceptoInscripcionCursoRepository;
    
    public long ConceptoInscripcionCursoServiceImpl.countAllConceptoInscripcionCursoes() {
        return conceptoInscripcionCursoRepository.count();
    }
    
    public void ConceptoInscripcionCursoServiceImpl.deleteConceptoInscripcionCurso(ConceptoInscripcionCurso conceptoInscripcionCurso) {
        conceptoInscripcionCursoRepository.delete(conceptoInscripcionCurso);
    }
    
    public ConceptoInscripcionCurso ConceptoInscripcionCursoServiceImpl.findConceptoInscripcionCurso(Long id) {
        return conceptoInscripcionCursoRepository.findOne(id);
    }
    
    public List<ConceptoInscripcionCurso> ConceptoInscripcionCursoServiceImpl.findAllConceptoInscripcionCursoes() {
        return conceptoInscripcionCursoRepository.findAll();
    }
    
    public List<ConceptoInscripcionCurso> ConceptoInscripcionCursoServiceImpl.findConceptoInscripcionCursoEntries(int firstResult, int maxResults) {
        return conceptoInscripcionCursoRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void ConceptoInscripcionCursoServiceImpl.saveConceptoInscripcionCurso(ConceptoInscripcionCurso conceptoInscripcionCurso) {
        conceptoInscripcionCursoRepository.save(conceptoInscripcionCurso);
    }
    
    public ConceptoInscripcionCurso ConceptoInscripcionCursoServiceImpl.updateConceptoInscripcionCurso(ConceptoInscripcionCurso conceptoInscripcionCurso) {
        return conceptoInscripcionCursoRepository.save(conceptoInscripcionCurso);
    }
    
}
