// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.coleadmin.repository;

import com.raze.coleadmin.domain.Curso;
import com.raze.coleadmin.repository.CursoRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect CursoRepository_Roo_Jpa_Repository {
    
    declare parents: CursoRepository extends JpaRepository<Curso, Long>;
    
    declare parents: CursoRepository extends JpaSpecificationExecutor<Curso>;
    
    declare @type: CursoRepository: @Repository;
    
}
